site_name: Generative AI Use Case Studies
site_url: https://georgechengtai.github.io/Generative-AI-use-case-studies
nav:
  - Home: index.md
  - What LLM Can Do:
      #- Agentic Workflow, Fully Explained: agent.md
    - What LLMs Can Actually Do Today: common-capacities.md
    - Software Explainer: 
      - NotebookLM: notebookLM.md
    - Functionalities as Chatbot (2024):
      - Content Creation: content-creation.md
      - Grading and Feedback: grading-and-feedback.md    
      - Role-Playing: role-playing.md      
      - Mentoring: mentor.md
    - Applications for Educational Purposes (2024):
      - AI-powered Avatars and Voice Cloning: aivideo.md
      - AI-powered Search Engines: search-engine.md
      - Virtual Characters for Learning: virtual-character.md
      - Personalised and Adaptive Learning: palearning.md
      - Literature Review: literature-review.md
      - Multimodality: multimodality.md
      - For SEN Students: sen.md
  - What LLM Cannot Do:
    - Common Questions About LLMs: common-faqs.md
    - Understanding LLMs - Beyond the Black Box:
      - Can AI Actually 'Think'?: explainability.md
      - ...and Why It Makes Stuff Up?: hallucination.md 
  - How to Prompt Chatbots:
    - Section Overview: pe_g.md
    - Guides:
      - Set the Context - Let AI Ask: pe_g1.md
      - Assign the Role - Who Serves Best?: pe_g2.md
      - Fix your Mind - Meta-Prompting: pe_g3.md
      - Forget What's Been Said: pe_g4.md
      - Further Reading: 
        - Prompting Skills - Now Baked Into AI: pe_g5.md 
        - pe_g6.md
    - Ready-Made Templates:
      - How to Master Any Topics via Reasoning Models?: pe_t1.md
      - How Not to Get Useless Responses?: pe_t2.md
      - pe_t3.md
      - pe_t4.md
      - pe_t5.md
      - pe_t6.md
      - pe_t7.md
      - pe_t8.md
  - Learn From Whose tried AI:
    - CUHK Use Case - Dr. Mok (ECO):
      - Benchmark Exam Answers in Economics: wallace_1.md
      - Address Student Research Challenges in Projects: wallace_2.md
      - Simplify, Understand and Convert Codes for Research: wallace_3.md
      - Learn Investment Strategy Through AI-Guided Simulations: wallace_4.md
      - Refining Business Proposals Through AI-Assisted Feedback: wallace_5.md
    - Case Studies/Experiences shared by other unversities:
      - Journalism and Communication: journalism-and-communication.md
      - Psychology: psychology.md
      - Social Work: social-work.md
      - Sociology: sociology.md
  - Where is AI Going:
    - Model Evolution:
      - After DeepSeel-R1 (Mar 2025): 2025_new_models.md
      - After GPT-4o (Jun 2024): flagship-models.md
      - GPT-4o (OpenAI): gpt4o.md
    - DeepSeek: 
      - Introduction: deepseek.md
      - For interested readers:
        - Technical Overview: deepseek-overview.md
        - Industry Impact: deepseek-impact.md
        - Societal Implications: deepseek-implications.md
        - Privacy Considerations: deepseek-privacy.md
        - Extra Resources: deepseek-resources.md
    - AI development (not just LLM):
      - Latest Breakthoughs & Tools (since Mar 2025): AI_development_tracker.md
      - Personal Finding and Sharing (outdated, 2024) : blog.md

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.sharing
    - navigation.footer
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    logo: fontawesome/solid/robot
  favicon: images/favicon.png
  language: en
  font:
    text: "Roboto"
    code: "Fire Code"
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - glightbox
  - git-revision-date
  - offline:
      enabled: !ENV [OFFLINE, false]
  # - privacy:
  #    log_level: error

extra:
  analytics:
    provider: google
    property: G-V49W4H5DHF
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
    cookies:
      analytics:
        name: Google Analytics
        checked: true


# extra:
  social:
    - icon: material/video-vintage
      link: https://www.iorad.com/help-center/162026?roleId=11284
      name: Tutorial on Iorad
  generator: false

extra_css:
  - style.css

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: table
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://www.cuhk.edu.hk/english/faculties/social-science.html" target="_blank" rel="noopener">Faculty of Social Science, CUHK</a> <a href="#__consent">[Change cookie settings]</a>